In [1]:
import pandas as pd

In [ ]:
# Convert Excel File to CSV Files
employment_sectors_by_city_df = pd.read_excel("../Resources/employment_sectors_by_city_no_note.xlsx")
employment_sectors_by_city_df

,City,Province,REF_DATE,UOM,Goods Producing,Agriculture,Extracting,Utilities,Construction,Manufacturing,...,Finance,"Professional, Scientific and Technical Services","Business, Building and Other Support Services",Educational Services,Healthcare and Social Assistance,"Information, Culture and Recreation",Accommocation and Food Services,Public Administration,Other Services,Total Employed
0,Calgary,Alberta,2024,Persons in thousands,218.1,4.1,52.5,9.9,94.6,57.0,...,62.9,137.3,35.1,61.3,123.2,41.9,60.2,40.8,31.7,1009.4
1,Edmonton,Alberta,2024,Persons in thousands,174.2,2.3,26.0,5.3,89.0,51.5,...,46.8,73.4,28.8,65.0,113.9,29.5,47.8,32.1,59.8,852.9
2,Montréal,Quebec,2024,Persons in thousands,156.9,2.4,1.6,5.8,38.5,108.6,...,81.0,148.9,41.9,88.8,156.0,71.1,67.1,36.5,42.0,1099.0
3,Ottawa,Ontario,2024,Persons in thousands,116.1,6.1,2.1,2.4,64.8,40.6,...,41.5,89.4,25.4,60.3,95.0,30.7,46.4,24.7,171.0,836.1
4,Toronto,Ontario,2024,Persons in thousands,611.8,4.4,6.1,23.3,223.7,354.2,...,456.0,548.5,140.5,264.5,434.4,175.8,180.8,134.5,140.0,3852.0
5,Vancouver,British Columbia,2024,Persons in thousands,71.3,3.5,8.1,NaN,38.8,19.5,...,22.1,41.4,15.6,35.4,80.8,23.5,34.5,18.5,45.0,467.9
6,Winnipeg,Manitoba,2024,Persons in thousands,76.2,NaN,NaN,3.5,29.4,41.4,...,35.6,26.4,12.9,42.0,71.6,17.5,23.9,18.2,28.7,447.5

In [ ]:
employment_sectors_by_city_df.to_csv('../Output/employment_sectors_by_city_df.csv', index=False)