In [1]:
# Dependencies
import pandas as pd

# Capital Cities Data Frame

### Source: https://rentals.ca/national-rent-report#rentalsca-data

In [2]:
# Create a capital_cities array
capital_cities = [
    ("St. John's", "Newfoundland and Labrador"),
    ("Charlottetown", "Prince Edward Island"),
    ("Halifax", "Nova Scotia"),
    ("Fredericton", "New Brunswick"),
    ("Québec", "Quebec"),
    ("Toronto", "Ontario"),
    ("Winnipeg", "Manitoba"),
    ("Regina", "Saskatchewan"),
    ("Edmonton", "Alberta"),
    ("Victoria", "British Columbia"),
    ("Whitehorse", "Yukon"),
    ("Yellowknife", "Northwest Territories"),
    ("Iqaluit", "Nunavut")
]

In [3]:
rent_data = [
    (1011, 1188),  # St. John's
    (0, 0),  # Charlottetown
    (2062, 2558),  # Halifax
    (0, 0),  # Fredericton
    (1249, 1760),  # Québec
    (2313, 2929),  # Toronto
    (1428, 1725),  # Winnipeg
    (1242, 1486),  # Regina
    (1310, 1656),  # Edmonton
    (2091, 2700),  # Victoria
    (0, 0),  # Whitehorse
    (0, 0),  # Yellowknife
    (0, 0),  # Iqaluit
]

In [4]:
# Combine into one list of dicts
data = []
for (city, province), (rent1, rent2) in zip(capital_cities, rent_data):
    data.append({
        "City": city,
        "Province": province,
        "1Bedroom": rent1,
        "2Bedroom": rent2
    })

In [5]:
# Create DataFrame
capital_cities_df = pd.DataFrame(data)
capital_cities_df

             City                   Province  1Bedroom  2Bedroom
0      St. John's  Newfoundland and Labrador      1011      1188
1   Charlottetown       Prince Edward Island         0         0
2         Halifax                Nova Scotia      2062      2558
3     Fredericton              New Brunswick         0         0
4          Québec                     Quebec      1249      1760
5         Toronto                    Ontario      2313      2929
6        Winnipeg                   Manitoba      1428      1725
7          Regina               Saskatchewan      1242      1486
8        Edmonton                    Alberta      1310      1656
9        Victoria           British Columbia      2091      2700
10     Whitehorse                      Yukon         0         0
11    Yellowknife      Northwest Territories         0         0
12        Iqaluit                    Nunavut         0         0

In [6]:
# # Save to CSV
# capital_cities_df.to_csv("Output/capital_cities_rents.csv", index=False)
# print("✅ Rent data for capital cities saved.")

# Major Cities Data Frame

### Source: https://loanscanada.ca/rent/average-rent-payments-in-canada/

In [7]:
# Create an array for Data
rent_data = [
    ("Vancouver", "British Columbia", 2653, 3541),
    ("Victoria", "British Columbia", 2116, 2743),
    ("Burnaby", "British Columbia", 2456, 3078),
    ("Kelowna", "British Columbia", 1914, 2375),
    ("Surrey", "British Columbia", 2056, 2521),
    ("Calgary", "Alberta", 1711, 2073),
    ("Edmonton", "Alberta", 1312, 1639),
    ("Regina", "Saskatchewan", 1243, 1429),
    ("Saskatoon", "Saskatchewan", 1183, 1387),
    ("Winnipeg", "Manitoba", 1360, 1760),
    ("Toronto", "Ontario", 2495, 3287),
    ("Ottawa", "Ontario", 2037, 2494),
    ("Mississauga", "Ontario", 2294, 2722),
    ("Etobicoke", "Ontario", 2255, 2799),
    ("Brampton", "Ontario", 2155, 2398),
    ("Scarborough", "Ontario", 2194, 2519),
    ("Hamilton", "Ontario", 1817, 2201),
    ("Montreal", "Quebec", 1743, 2280),
    ("Laval", "Quebec", 1615, 1992),
    ("Quebec City", "Quebec", 1305, 1711),
    ("Halifax", "Nova Scotia", 1938, 2336)
]

In [8]:
# Create DataFrame
major_cities_df = pd.DataFrame(rent_data, columns=["City", "Province", "1Bedroom", "2Bedroom"])
major_cities_df

           City          Province  1Bedroom  2Bedroom
0     Vancouver  British Columbia      2653      3541
1      Victoria  British Columbia      2116      2743
2       Burnaby  British Columbia      2456      3078
3       Kelowna  British Columbia      1914      2375
4        Surrey  British Columbia      2056      2521
5       Calgary           Alberta      1711      2073
6      Edmonton           Alberta      1312      1639
7        Regina      Saskatchewan      1243      1429
8     Saskatoon      Saskatchewan      1183      1387
9      Winnipeg          Manitoba      1360      1760
10      Toronto           Ontario      2495      3287
11       Ottawa           Ontario      2037      2494
12  Mississauga           Ontario      2294      2722
13    Etobicoke           Ontario      2255      2799
14     Brampton           Ontario      2155      2398
15  Scarborough           Ontario      2194      2519
16     Hamilton           Ontario      1817      2201
17     Montreal            Quebec      1743      2280
18        Laval            Quebec      1615      1992
19  Quebec City            Quebec      1305      1711
20      Halifax       Nova Scotia      1938      2336

In [9]:
# # Save to CSV
# major_cities_df.to_csv("Output/major_cities_rents.csv", index=False)

# print("✅ CSV file 'major_cities_rent_with_province.csv' created successfully.")

# Top 15 Major Cities in Canada

### Source: https://rentals.ca/national-rent-report#rentalsca-data

In [10]:
# Dependencies
import pandas as pd

In [11]:
# Read the raw CSV file (encoding fixed)
df = pd.read_csv("Resources/cities_rents.csv", encoding="ISO-8859-1")

In [12]:
# Rename relevant columns for clarity
df.columns = ['Rank', 'City', 'Rent_1Bedroom', 'M/M_1B', 'Y/Y_1B', 'Rent_2Bedroom', 'M/M_2B', 'Y/Y_2B']

In [13]:
# Strip whitespace from city names
df['City'] = df['City'].str.strip()

In [14]:
# Define the 15 cities to include
target_cities = [
    "Toronto", "Ottawa", "Mississauga", "Hamilton",
    "Montreal", "Quebec City", "Vancouver", "Victoria",
    "Calgary", "Edmonton", "Winnipeg", "Saskatoon",
    "Regina", "Halifax", "St. John's"
]

In [15]:
# Filter the DataFrame to only include those 15 cities
df_filtered = df[df['City'].isin(target_cities)].copy()

In [16]:
# Map each city to its province
province_map = {
    "Toronto": "Ontario", "Ottawa": "Ontario", "Mississauga": "Ontario", "Hamilton": "Ontario",
    "Montreal": "Quebec", "Quebec City": "Quebec",
    "Vancouver": "British Columbia", "Victoria": "British Columbia",
    "Calgary": "Alberta", "Edmonton": "Alberta",
    "Winnipeg": "Manitoba", "Saskatoon": "Saskatchewan", "Regina": "Saskatchewan",
    "Halifax": "Nova Scotia", "St. John's": "Newfoundland and Labrador"
}
df_filtered['Province'] = df_filtered['City'].map(province_map)

In [17]:
# Clean rent values: remove $ and commas, convert to float
df_filtered['Rent_1Bedroom'] = df_filtered['Rent_1Bedroom'].replace('[\$,]', '', regex=True).astype(float)
df_filtered['Rent_2Bedroom'] = df_filtered['Rent_2Bedroom'].replace('[\$,]', '', regex=True).astype(float)

In [18]:
# Keep only relevant columns
df_final = df_filtered[['City', 'Province', 'Rent_1Bedroom', 'Rent_2Bedroom']]

In [19]:
# # Save to a new CSV file
# df_final.to_csv("Output/Major_15_cities.csv", index=False)
# print("✅ CSV file 'Major_15_cities.csv' created successfully.")

In [20]:
df_final

           City                   Province  Rent_1Bedroom  Rent_2Bedroom
1     Vancouver           British Columbia         2531.0         3430.0
5       Toronto                    Ontario         2313.0         2929.0
10  Mississauga                    Ontario         2174.0         2605.0
13     Victoria           British Columbia         2091.0         2700.0
16      Halifax                Nova Scotia         2062.0         2558.0
20       Ottawa                    Ontario         2020.0         2578.0
37     Montreal                     Quebec         1724.0         2236.0
38     Hamilton                    Ontario         1720.0         2097.0
45      Calgary                    Alberta         1588.0         1928.0
49     Winnipeg                   Manitoba         1428.0         1725.0
52     Edmonton                    Alberta         1310.0         1656.0
53    Saskatoon               Saskatchewan         1276.0         1516.0
55  Quebec City                     Quebec         1249.0         1760.0
56       Regina               Saskatchewan         1242.0         1486.0
59   St. John's  Newfoundland and Labrador         1011.0         1188.0

# Top 10 Major Cities Rent in Canada

### Source: https://rentals.ca/national-rent-report#rentalsca-data

In [21]:
# Read the raw CSV file (encoding fixed)
df = pd.read_csv("Resources/cities_rents.csv", encoding="ISO-8859-1")

In [22]:
# Rename relevant columns for clarity
df.columns = ['Rank', 'City', 'Rent_1Bedroom', 'M/M_1B', 'Y/Y_1B', 'Rent_2Bedroom', 'M/M_2B', 'Y/Y_2B']

In [23]:
# Strip whitespace from city names
df['City'] = df['City'].str.strip()

In [24]:
# Define the 10 cities to include
target_cities = [
    "Toronto","Montreal","Calgary", "Ottawa", "Edmonton", "Winnipeg",
    "Mississauga", "Vancouver", "Brampton", "Hamilton",
]

In [25]:
# Filter the DataFrame to only include those 10 cities
df_filtered = df[df['City'].isin(target_cities)].copy()

In [26]:
# Map each city to its province
province_map = {
    "Toronto": "Ontario", "Montreal": "Quebec", "Calgary": "Alberta",
    "Ottawa": "Ontario", "Edmonton": "Alberta", "Winnipeg": "Manitoba",
    "Mississauga": "Ontario", "Vancouver": "British Columbia", "Brampton": "Ontario",
    "Hamilton": "Ontario",
}
df_filtered['Province'] = df_filtered['City'].map(province_map)

In [27]:
# Clean rent values: remove $ and commas, convert to float
df_filtered['Rent_1Bedroom'] = df_filtered['Rent_1Bedroom'].replace('[\$,]', '', regex=True).astype(float)
df_filtered['Rent_2Bedroom'] = df_filtered['Rent_2Bedroom'].replace('[\$,]', '', regex=True).astype(float)

In [28]:
# Map each city to its population
population_map = {
    "Toronto": 2794356, "Montreal": 1762949, "Calgary": 1306784,
    "Ottawa": 1017449, "Edmonton": 1010899, "Winnipeg": 749607,
    "Mississauga": 717961, "Vancouver": 662248, "Brampton": 656480,
    "Hamilton": 569353,
}
df_filtered['Population(2021)'] = df_filtered['City'].map(population_map)

In [29]:
# Keep only relevant columns
df_final = df_filtered[['City', 'Province','Population(2021)', 'Rent_1Bedroom', 'Rent_2Bedroom']]

In [30]:
df_final

,City,Province,Population(2021),Rent_1Bedroom,Rent_2Bedroom
1,Vancouver,British Columbia,662248,2531.0,3430.0
5,Toronto,Ontario,2794356,2313.0,2929.0
10,Mississauga,Ontario,717961,2174.0,2605.0
20,Ottawa,Ontario,1017449,2020.0,2578.0
25,Brampton,Ontario,656480,1919.0,2276.0
37,Montreal,Quebec,1762949,1724.0,2236.0
38,Hamilton,Ontario,569353,1720.0,2097.0
45,Calgary,Alberta,1306784,1588.0,1928.0
49,Winnipeg,Manitoba,749607,1428.0,1725.0
52,Edmonton,Alberta,1010899,1310.0,1656.0

In [31]:
# Save to a new CSV file
df_final.to_csv("Output/Major_10_cities.csv", index=False)
print("✅ CSV file 'Major_10_cities.csv' created successfully.")

✅ CSV file 'Major_10_cities.csv' created successfully.